CHROME_DRIVER_PATH = "D:\QA\Website_Nexalinx_Testing\drivers"
BASE_URL = "https://www.nexalinx.com/"
HOME_PAGE_URL = "https://www.nexalinx.com/#/home"
PORTFOLIO_PAGE_URL = "https://www.nexalinx.com/#/portfolio"
BLOG_PAGE_URL = "https://www.nexalinx.com/#/blog"
CONTACT_PAGE_URL = "https://www.nexalinx.com/#/contact"
ABOUT_US_PAGE_URL = "https://www.nexalinx.com/#/about-us"
OUR_TEAM_PAGE_URL = "https://www.nexalinx.com/#/team"
OUR_VISION_PAGE_URL = "https://www.nexalinx.com/#/vision"
OUR_MISSION_PAGE_URL = "https://www.nexalinx.com/#/mission"
BLOG_DETAILS_PAGE_URL = "https://www.nexalinx.com/#/blog-details"
ANGULARJS_PAGE_URL = "https://www.nexalinx.com/#/angular"
REACTJS_PAGE_URL = "https://www.nexalinx.com/#/reactjs"
NODEJS_PAGE_URL = "https://www.nexalinx.com/#/nodejs"
PYTHON_PAGE_URL = "https://www.nexalinx.com/#/python"
VUEJS_PAGE_URL = "https://www.nexalinx.com/#/vuejs"
MAGNETO_PAGE_URL = "https://www.nexalinx.com/#/magento"
PHP_PAGE_URL = "https://www.nexalinx.com/#/php"
LARAVEL_PAGE_URL = "https://www.nexalinx.com/#/laravel"
WORDPRESS_PAGE_URL = "https://www.nexalinx.com/#/wordpress"
ASPNET_PAGE_URL = "https://www.nexalinx.com/#/aspnet"
OFFSHORE_PAGE_URL = "https://www.nexalinx.com/#/developmentcompany"
FULL_STACK_PAGE_URL = "https://www.nexalinx.com/#/full-stack-development"
AMAZON_WEB_SERVICES_PAGE_URL = "https://www.nexalinx.com/#/amazon-web-services"
IT_CONSULTING_PAGE_URL = "https://www.nexalinx.com/#/it-consulting-services"
SOFTWARE_MAINTEANCE_PAGE_URL = "https://www.nexalinx.com/#/software-maintenance-support-services"
SOFTWARE_QA_PAGE_URL = "https://www.nexalinx.com/#/software-qa-and-testing-services"
UI_UX_PAGE_URL = "https://www.nexalinx.com/#/ui-ux-design"
DATABSE_MANAGEMENT_PAGE_URL = "https://www.nexalinx.com/#/database-management-services"
CYBER_SECURITY_PAGE_URL = "https://www.nexalinx.com/#/cyber-security"
PROGRESSIVE_WEB_PAGE_URL = "https://www.nexalinx.com/#/progressive-web-app-development"
ERP_PAGE_URL = "https://www.nexalinx.com/#/erp-software-development-services"
JAVA_PAGE_URL = "https://www.nexalinx.com/#/java-development"




